"""Creacion inicial de tablas

Revision ID: 2ff4263ff3eb
Revises: 
Create Date: 2026-05-06 00:15:02.157552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ff4263ff3eb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sesiones_asistencia',
    sa.Column('id_sesion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_materia', sa.String(length=36), nullable=False),
    sa.Column('id_docente', sa.String(length=36), nullable=False),
    sa.Column('estado_sesion', sa.Enum('ACTIVA', 'CERRADA', 'EXPIRADA', name='estado_sesion_enum', native_enum=False, length=20), nullable=False),
    sa.Column('fecha_hora_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_hora_limite_presente', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_hora_fin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_hora_cierre', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id_sesion')
    )
    op.create_index('idx_unica_sesion_activa_por_materia', 'sesiones_asistencia', ['id_materia'], unique=True, postgresql_where=sa.text("estado_sesion = 'ACTIVA'"))
    op.create_index(op.f('ix_sesiones_asistencia_estado_sesion'), 'sesiones_asistencia', ['estado_sesion'], unique=False)
    op.create_index(op.f('ix_sesiones_asistencia_id_docente'), 'sesiones_asistencia', ['id_docente'], unique=False)
    op.create_index(op.f('ix_sesiones_asistencia_id_materia'), 'sesiones_asistencia', ['id_materia'], unique=False)
    op.create_table('registros_asistencia',
    sa.Column('id_asistencia', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_sesion', sa.Integer(), nullable=False),
    sa.Column('id_alumno', sa.String(length=36), nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('estado_asistencia', sa.Enum('PRESENTE', 'RETARDO', 'AUSENTE', name='estado_asistencia_enum', native_enum=False, length=20), nullable=False),
    sa.Column('identificador_qr', sa.String(length=64), nullable=True),
    sa.Column('fecha_hora_emision_qr', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_hora_registro', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('metodo_registro', sa.Enum('QR', 'SISTEMA', name='metodo_registro_enum', native_enum=False, length=20), nullable=False),
    sa.Column('observaciones', sa.String(length=250), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['id_sesion'], ['sesiones_asistencia.id_sesion'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_asistencia'),
    sa.UniqueConstraint('id_sesion', 'id_alumno', name='uq_registro_asistencia_sesion_alumno'),
    sa.UniqueConstraint('identificador_qr')
    )
    op.create_index(op.f('ix_registros_asistencia_estado_asistencia'), 'registros_asistencia', ['estado_asistencia'], unique=False)
    op.create_index(op.f('ix_registros_asistencia_fecha_hora_registro'), 'registros_asistencia', ['fecha_hora_registro'], unique=False)
    op.create_index(op.f('ix_registros_asistencia_id_alumno'), 'registros_asistencia', ['id_alumno'], unique=False)
    op.create_index(op.f('ix_registros_asistencia_id_sesion'), 'registros_asistencia', ['id_sesion'], unique=False)
    op.create_index(op.f('ix_registros_asistencia_matricula'), 'registros_asistencia', ['matricula'], unique=False)
    op.create_table('tokens_qr_usados',
    sa.Column('id_token_qr_usado', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_sesion', sa.Integer(), nullable=False),
    sa.Column('id_alumno', sa.String(length=36), nullable=False),
    sa.Column('identificador_unico_qr', sa.String(length=64), nullable=False),
    sa.Column('huella_token', sa.String(length=128), nullable=False),
    sa.Column('fecha_hora_emision', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_hora_expiracion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_hora_uso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resultado_validacion', sa.Enum('ACEPTADO', 'RECHAZADO', 'EXPIRADO', 'DUPLICADO', name='resultado_validacion_qr_enum', native_enum=False, length=20), nullable=False),
    sa.Column('motivo_rechazo', sa.String(length=150), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['id_sesion'], ['sesiones_asistencia.id_sesion'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_token_qr_usado')
    )
    op.create_index(op.f('ix_tokens_qr_usados_fecha_hora_expiracion'), 'tokens_qr_usados', ['fecha_hora_expiracion'], unique=False)
    op.create_index(op.f('ix_tokens_qr_usados_huella_token'), 'tokens_qr_usados', ['huella_token'], unique=True)
    op.create_index(op.f('ix_tokens_qr_usados_id_alumno'), 'tokens_qr_usados', ['id_alumno'], unique=False)
    op.create_index(op.f('ix_tokens_qr_usados_id_sesion'), 'tokens_qr_usados', ['id_sesion'], unique=False)
    op.create_index(op.f('ix_tokens_qr_usados_identificador_unico_qr'), 'tokens_qr_usados', ['identificador_unico_qr'], unique=True)
    op.create_index(op.f('ix_tokens_qr_usados_resultado_validacion'), 'tokens_qr_usados', ['resultado_validacion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tokens_qr_usados_resultado_validacion'), table_name='tokens_qr_usados')
    op.drop_index(op.f('ix_tokens_qr_usados_identificador_unico_qr'), table_name='tokens_qr_usados')
    op.drop_index(op.f('ix_tokens_qr_usados_id_sesion'), table_name='tokens_qr_usados')
    op.drop_index(op.f('ix_tokens_qr_usados_id_alumno'), table_name='tokens_qr_usados')
    op.drop_index(op.f('ix_tokens_qr_usados_huella_token'), table_name='tokens_qr_usados')
    op.drop_index(op.f('ix_tokens_qr_usados_fecha_hora_expiracion'), table_name='tokens_qr_usados')
    op.drop_table('tokens_qr_usados')
    op.drop_index(op.f('ix_registros_asistencia_matricula'), table_name='registros_asistencia')
    op.drop_index(op.f('ix_registros_asistencia_id_sesion'), table_name='registros_asistencia')
    op.drop_index(op.f('ix_registros_asistencia_id_alumno'), table_name='registros_asistencia')
    op.drop_index(op.f('ix_registros_asistencia_fecha_hora_registro'), table_name='registros_asistencia')
    op.drop_index(op.f('ix_registros_asistencia_estado_asistencia'), table_name='registros_asistencia')
    op.drop_table('registros_asistencia')
    op.drop_index(op.f('ix_sesiones_asistencia_id_materia'), table_name='sesiones_asistencia')
    op.drop_index(op.f('ix_sesiones_asistencia_id_docente'), table_name='sesiones_asistencia')
    op.drop_index(op.f('ix_sesiones_asistencia_estado_sesion'), table_name='sesiones_asistencia')
    op.drop_index('idx_unica_sesion_activa_por_materia', table_name='sesiones_asistencia', postgresql_where=sa.text("estado_sesion = 'ACTIVA'"))
    op.drop_table('sesiones_asistencia')
    # ### end Alembic commands ###
