"""create initial periodos materias schema

Revision ID: 92a07c48d27c
Revises: 
Create Date: 2026-05-06 08:32:25.726031

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '92a07c48d27c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materias_catalogo',
    sa.Column('materia_catalogo_id', sa.UUID(), nullable=False),
    sa.Column('clave', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('materia_catalogo_id'),
    sa.UniqueConstraint('clave')
    )
    op.create_table('periodos',
    sa.Column('periodo_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.CheckConstraint('fecha_inicio <= fecha_fin', name='ck_periodos_fechas_validas'),
    sa.PrimaryKeyConstraint('periodo_id')
    )
    op.create_index('uq_periodos_unico_activo', 'periodos', ['activo'], unique=True, postgresql_where=sa.text('activo IS true'))
    op.create_table('planes_estudio',
    sa.Column('plan_estudio_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('plan_estudio_id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('materia_plan_estudio',
    sa.Column('materia_plan_estudio_id', sa.UUID(), nullable=False),
    sa.Column('materia_catalogo_id', sa.UUID(), nullable=False),
    sa.Column('plan_estudio_id', sa.UUID(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['materia_catalogo_id'], ['materias_catalogo.materia_catalogo_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_estudio_id'], ['planes_estudio.plan_estudio_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('materia_plan_estudio_id'),
    sa.UniqueConstraint('materia_catalogo_id', 'plan_estudio_id', name='uq_materia_plan_estudio')
    )
    op.create_table('materias_ofertadas',
    sa.Column('materia_ofertada_id', sa.UUID(), nullable=False),
    sa.Column('periodo_id', sa.UUID(), nullable=False),
    sa.Column('materia_catalogo_id', sa.UUID(), nullable=False),
    sa.Column('nrc', sa.String(length=5), nullable=False),
    sa.Column('seccion', sa.String(length=100), nullable=False),
    sa.Column('docente_id', sa.UUID(), nullable=True),
    sa.Column('docente_nombre', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['materia_catalogo_id'], ['materias_catalogo.materia_catalogo_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodos.periodo_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('materia_ofertada_id'),
    sa.UniqueConstraint('periodo_id', 'nrc', name='uq_materia_ofertada_periodo_nrc')
    )
    op.create_table('materia_horarios',
    sa.Column('materia_horario_id', sa.UUID(), nullable=False),
    sa.Column('materia_ofertada_id', sa.UUID(), nullable=False),
    sa.Column('dia', sa.String(length=2), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('salon', sa.String(length=50), nullable=True),
    sa.CheckConstraint('hora_inicio < hora_fin', name='ck_materia_horarios_horas_validas'),
    sa.ForeignKeyConstraint(['materia_ofertada_id'], ['materias_ofertadas.materia_ofertada_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('materia_horario_id'),
    sa.UniqueConstraint('materia_ofertada_id', 'dia', 'hora_inicio', 'hora_fin', 'salon', name='uq_materia_horario_unico')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('materia_horarios')
    op.drop_table('materias_ofertadas')
    op.drop_table('materia_plan_estudio')
    op.drop_table('planes_estudio')
    op.drop_index('uq_periodos_unico_activo', table_name='periodos', postgresql_where=sa.text('activo IS true'))
    op.drop_table('periodos')
    op.drop_table('materias_catalogo')
    # ### end Alembic commands ###