"""creacion_inicial_de_tablas

Revision ID: 578789242824
Revises: 
Create Date: 2026-05-18 07:05:02.081195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '578789242824'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reportes_generados',
    sa.Column('reporte_id', sa.UUID(), nullable=False),
    sa.Column('tipo_reporte', sa.String(length=30), nullable=False),
    sa.Column('formato', sa.String(length=10), nullable=False),
    sa.Column('periodo_id', sa.UUID(), nullable=True),
    sa.Column('materia_id', sa.UUID(), nullable=True),
    sa.Column('docente_id', sa.UUID(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('reporte_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reportes_generados')
    # ### end Alembic commands ###
