"""create calificaciones tables

Revision ID: e25e0693b7d6
Revises: 
Create Date: 2026-05-07 09:24:54.657649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e25e0693b7d6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ponderaciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('materia_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('porcentaje', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('porcentaje > 0 AND porcentaje <= 100', name='chk_ponderacion_porcentaje'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('materia_id', 'nombre', name='uq_ponderacion_materia_nombre')
    )
    op.create_index(op.f('ix_ponderaciones_materia_id'), 'ponderaciones', ['materia_id'], unique=False)
    op.create_table('actividades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('materia_id', sa.UUID(), nullable=False),
    sa.Column('ponderacion_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('valor_maximo', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fecha_aplicacion', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado IN ('activa', 'cerrada', 'cancelada')", name='chk_actividad_estado'),
    sa.CheckConstraint('valor_maximo > 0', name='chk_actividad_valor_maximo'),
    sa.ForeignKeyConstraint(['ponderacion_id'], ['ponderaciones.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ponderacion_id', 'nombre', name='uq_actividad_ponderacion_nombre')
    )
    op.create_index(op.f('ix_actividades_materia_id'), 'actividades', ['materia_id'], unique=False)
    op.create_index(op.f('ix_actividades_ponderacion_id'), 'actividades', ['ponderacion_id'], unique=False)
    op.create_table('calificaciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actividad_id', sa.UUID(), nullable=False),
    sa.Column('alumno_id', sa.UUID(), nullable=False),
    sa.Column('calificacion', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('calificacion >= 0', name='chk_calificacion_minima'),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividades.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actividad_id', 'alumno_id', name='uq_calificacion_actividad_alumno')
    )
    op.create_index(op.f('ix_calificaciones_actividad_id'), 'calificaciones', ['actividad_id'], unique=False)
    op.create_index(op.f('ix_calificaciones_alumno_id'), 'calificaciones', ['alumno_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calificaciones_alumno_id'), table_name='calificaciones')
    op.drop_index(op.f('ix_calificaciones_actividad_id'), table_name='calificaciones')
    op.drop_table('calificaciones')
    op.drop_index(op.f('ix_actividades_ponderacion_id'), table_name='actividades')
    op.drop_index(op.f('ix_actividades_materia_id'), table_name='actividades')
    op.drop_table('actividades')
    op.drop_index(op.f('ix_ponderaciones_materia_id'), table_name='ponderaciones')
    op.drop_table('ponderaciones')
    # ### end Alembic commands ###
